stages:
  - test
  - release

variables:
  PLUGIN_NAME: ifauthex

unit_test:
  stage: test
  image: php:8.2.1
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git # curl ca-certificates libxml2-dev libonig-dev
    - git clone https://github.com/splitbrain/dokuwiki.git
    - pushd dokuwiki/lib/plugins
    - ln -s $CI_PROJECT_DIR "${PLUGIN_NAME}"
    - popd
    - pushd dokuwiki/_test
    - php fetchphpunit.php
    - popd
  script:
    - cd dokuwiki/_test
    - php phpunit.phar --group "plugin_${PLUGIN_NAME}"

package:
  image: alpine
  stage: release
  only:
    - tags
  before_script:
    - apk --update --no-cache add zip
  script:
    - zip -r "${PLUGIN_NAME}.zip" *
  artifacts:
    paths:
      - "${PLUGIN_NAME}.zip"
  variables:
    GIT_STRATEGY: clone
